### ISSUE TITLE
Bump package tag for ITK v5.3.0

### ISSUE THREAD

**Issue by tbirdso** [InsightSoftwareConsortium/ITKCuberille#76]
`setup.py` should be amended as follows:
- The minor version number should be bumped (i.e. 2.5.0 -> 2.6.0);
- The required minimum ITK version should be bumped to v5.3.0

After these changes are merged a new 2.6.0 release should be tagged in order to automatically upload wheels to PyPI.

**Comment by tbirdso** [comment]
@PranjalSahu would you be willing to take this on? Please let me know if you have questions.

**Comment by thewtex** [comment]
Thanks, @PranjalSahu @tbirdso !
